// Generated by CoffeeScript 1.7.1
(function() {
  var sqlHelper;

  sqlHelper = require('../src/index')({
    dbConfig: {
      host: '192.168.1.88',
      user: 'root',
      port: 3306,
      password: '',
      database: 'test'
    }
  });


  /*
      test if node unit work well
   */

  exports.testNodeUnitWork = function(test) {
    test.ok(1 === 1);
    return test.done();
  };


  /*
      test mysql connection ok
   */

  exports.testCreateConnection = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select 1+1 as result;";
    return conn.query(sql, [], function(err, result) {
      console.dir(err);
      test.ok(!err);
      test.ok(result.length > 0);
      test.ok(result[0].result === 2);
      conn.end();
      return test.done();
    });
  };

  exports.testExecute = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select * from test;";
    return conn.execute(sql, function(err, result) {
      test.ok(!err);
      test.ok(result.length > 0);
      conn.end();
      return test.done();
    });
  };

  exports.test$Execute = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select 1+1 as result;";
    return conn.$execute(sql, function(err, result) {
      test.ok(!conn._socket._readableState.ended);
      test.ok(!err);
      test.ok(result.length > 0);
      test.ok(result[0].result === 2);
      return setTimeout(function() {
        test.ok(conn._socket._readableState.ended);
        return test.done();
      }, 100);
    });
  };

  exports.testExecuteScalar = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select 1+1 as result,1+2 as result2;";
    return conn.executeScalar(sql, function(err, result) {
      test.ok(!err);
      test.ok(result === 2);
      return test.done();
    });
  };

  exports.testEndConnection = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select 1 + 1 as result;";
    return conn.executeScalar(sql, function(err, result) {
      test.ok(!err);
      test.ok(result === 2);
      return conn.end(function() {
        var e;
        try {
          conn.end();
        } catch (_error) {
          e = _error;
          test.ok(e);
        }
        return test.done();
      });
    });
  };

}).call(this);

//# sourceMappingURL=testConnect.map
