// Generated by CoffeeScript 1.7.1
(function() {
  var dbConfig, sqlHelper;

  dbConfig = {
    host: '127.0.0.1',
    user: 'root',
    port: 3306,
    password: ' ',
    database: 'mockup'
  };

  sqlHelper = require('../lib/index')({
    dbConfig: dbConfig
  });


  /*
      test if node unit work well
   */

  exports.testNodeUnitWork = function(test) {
    test.ok(1 === 1);
    return test.done();
  };


  /*
      test mysql connection ok
   */

  exports.testCreateConnection = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection(dbConfig);
    conn.connect();
    sql = "select 1+1 as result;";
    return conn.query(sql, [], function(err, result) {
      test.ok(!err);
      test.ok(result.length > 0);
      test.ok(result[0].result === 2);
      return test.done();
    });
  };

  exports.testExecute = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection(dbConfig);
    conn.connect();
    sql = "select 1+1 as result;";
    return conn.execute(sql, [], function(err, result) {
      test.ok(!err);
      test.ok(result.length > 0);
      test.ok(result[0].result === 2);
      return test.done();
    });
  };

  exports.test$Execute = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection();
    sql = "select 1+1 as result;";
    return conn.$execute(sql, function(err, result) {
      test.ok(!conn._socket._readableState.ended);
      test.ok(!err);
      test.ok(result.length > 0);
      test.ok(result[0].result === 2);
      return setTimeout(function() {
        test.ok(conn._socket._readableState.ended);
        return test.done();
      }, 100);
    });
  };

  exports.testExecuteScalar = function(test) {
    var conn, sql;
    conn = sqlHelper.createConnection(dbConfig);
    conn.connect();
    sql = "select 1+1 as result,1+2 as result2;";
    return conn.executeScalar(sql, function(err, result) {
      test.ok(!err);
      test.ok(result === 2);
      return test.done();
    });
  };

}).call(this);

//# sourceMappingURL=testConnect.map
